{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-api",
    "version": "6.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "6.0.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "6.0.1"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-6.0.1.jar",
          "url": "junit-jupiter-api-6.0.1.jar",
          "size": 250699,
          "sha512": "f020c23a5f0b68b285537281d30a2f7d85ff93e65dee4fa37303729a3874bcd85de5bead1726c1b80fde07b2ee248ccf339059f4e9f580a5b23237f90057351d",
          "sha256": "a3ca8c7e567436093e4a6703d5d4aac02dbea36106ea32fd1367b56de20d4e02",
          "sha1": "fd95c21739621a27658aada0ac23ff3d354beaa5",
          "md5": "13c345298eea2b62b3385271b716e6aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "6.0.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "6.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-6.0.1.jar",
          "url": "junit-jupiter-api-6.0.1.jar",
          "size": 250699,
          "sha512": "f020c23a5f0b68b285537281d30a2f7d85ff93e65dee4fa37303729a3874bcd85de5bead1726c1b80fde07b2ee248ccf339059f4e9f580a5b23237f90057351d",
          "sha256": "a3ca8c7e567436093e4a6703d5d4aac02dbea36106ea32fd1367b56de20d4e02",
          "sha1": "fd95c21739621a27658aada0ac23ff3d354beaa5",
          "md5": "13c345298eea2b62b3385271b716e6aa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-6.0.1-javadoc.jar",
          "url": "junit-jupiter-api-6.0.1-javadoc.jar",
          "size": 5074872,
          "sha512": "41b37f2c05e23520989993c6d65c6652cec8765947b30afd0c764fda8907628aa0391b09325d80c8c9c561af4d7d14d5382a174955235a3cb39cd6877ce62fd0",
          "sha256": "d8687eb1aef4419e46a9f32877d78184cfcd65e4f4df9fb6dd608193eba43c57",
          "sha1": "3afbd23dd462fff6d31120a19ee1b6c10054556a",
          "md5": "227cf7c7b653569c8ad83a4ee4372785"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-6.0.1-sources.jar",
          "url": "junit-jupiter-api-6.0.1-sources.jar",
          "size": 249142,
          "sha512": "2299732536611f59d7098f6dad328b128ae5810d6c55cba7fd8147ccba8cda2afc9be40b6d3f04b9c9f7a553fe0ffcf6b68b9750a68294ac8b2cb67f469acd81",
          "sha256": "b660b2445151341b45d0ee6243135ec773c93111ac0288586b2abb732520f3fd",
          "sha1": "554fe6a5dce83d13bb9b7bb56c239a4c1f46a5e8",
          "md5": "69083953be2880bedf80a24b453cc739"
        }
      ]
    }
  ]
}
